name: Deploy to Ubuntu

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/multilevel/multilevel-frontend
            git pull
            yarn build:only
            yarn build
            pm2 reload mlm_prod
